### ISSUE TITLE
Type error in latest version (1.3.7) with QGIS 3.34.x

### ISSUE THREAD

**Issue by voisardf** [opengisch/qgis_geomapfish_locator#14]
Hi, 
several persons report the same type error for the latest GeomapfishLocator Version under QGIS 3.34.x and 3.28.x:

`TypeError: QgsMapCanvas.flashGeometries(): argument 6 has unexpected type 'float' 
Traceback (most recent call last):
  File "C:\Users/voisardf/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geomapfish_locator\core\locator_filter.py", line 247, in triggerResult
    self.map_canvas.flashGeometries(
TypeError: QgsMapCanvas.flashGeometries(): argument 6 has unexpected type 'float'`

Version de Python : 3.12.3 (main, Apr 14 2024, 17:21:43) [MSC v.1938 64 bit (AMD64)] 
Version de QGIS : 3.34.7-Prizren Prizren, 6f7d735c 

`Traceback (most recent call last):
              File "C:\Users/CornutCa/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\geomapfish_locator\core\locator_filter.py", line 228, in triggerResult
              self.map_canvas.flashGeometries([geometry], self.crs, color1, color2, nflash, self.settings.value('highlight_duration')/nflash*1000)
             TypeError: QgsMapCanvas.flashGeometries(): argument 6 has unexpected type 'float'
`

the map is still recentered, but there is no hilighting of the object.

many thanks for having a look at it when you find a moment

**Comment by 3nids** [comment]
@voisardf can you check if 1.3.8 fixes this? cheers!

**Comment by voisardf** [comment]
Thanks for the VERY fast fix! 🥇 😃
I checked the update using QGIS 3.34 and 3.28 and it works perfectly for me. I also asked my collegues to verify, but I think it's ok.
